parameters:
  exchangeRateApiKey: '%env(EXCHANGE_RATE_API_KEY)%'

services:
  _defaults:
    autowire: false
    autoconfigure: false

  App\Command\ShowSavingsCommand:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@App\RateUpdater\RateUpdater'
    tags:
      - { name: 'console.command', command: 'savings:show' }

  App\RateUpdater\Provider\CoinGeckoRateProvider:
    tags: ['app.rate-updater.provider']

  App\RateUpdater\Provider\ExchangeRateRateProvider:
    tags: ['app.rate-updater.provider']
    arguments:
      - '%exchangeRateApiKey%'

  App\RateUpdater\RateUpdater:
    arguments:
      - !tagged app.rate-updater.provider
      - '@doctrine.orm.default_entity_manager'
